// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMrMajNl25SbOZI61qNvmeo2E81wlXH8Q',
    appId: '1:608731956334:web:3b12af3b2985728b5d127f',
    messagingSenderId: '608731956334',
    projectId: 'rentsy-721c8',
    authDomain: 'rentsy-721c8.firebaseapp.com',
    storageBucket: 'rentsy-721c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKLUFlREIn8fi4bt0ljlg0m0qC5rc-Vk',
    appId: '1:608731956334:android:6b9678daeb0dc4505d127f',
    messagingSenderId: '608731956334',
    projectId: 'rentsy-721c8',
    storageBucket: 'rentsy-721c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkrrzQJaWYHQWvQOth71hWsGCjfRtRpM',
    appId: '1:608731956334:ios:d093c626069f70245d127f',
    messagingSenderId: '608731956334',
    projectId: 'rentsy-721c8',
    storageBucket: 'rentsy-721c8.firebasestorage.app',
    iosBundleId: 'com.example.saved',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIkrrzQJaWYHQWvQOth71hWsGCjfRtRpM',
    appId: '1:608731956334:ios:d093c626069f70245d127f',
    messagingSenderId: '608731956334',
    projectId: 'rentsy-721c8',
    storageBucket: 'rentsy-721c8.firebasestorage.app',
    iosBundleId: 'com.example.saved',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMrMajNl25SbOZI61qNvmeo2E81wlXH8Q',
    appId: '1:608731956334:web:63eebc2a5eb7687d5d127f',
    messagingSenderId: '608731956334',
    projectId: 'rentsy-721c8',
    authDomain: 'rentsy-721c8.firebaseapp.com',
    storageBucket: 'rentsy-721c8.firebasestorage.app',
  );
}
